const busInfo = {
      Buses: [
        {
          busId:"B32213",
          name: 'BABA Travels',
          departure: '20:00',
          duration: '16h 40m',
          arrival: '12:40',
          fare: 1200,
          seatAvailable: 15,
          bustype: 'AC Sleeper(2+1)',
          rating: 4.5,
          source: "Nagpur" ,
          destination: 'Nashik',
        },
        {
            busId:"S31223",
            name: 'Saini Travels',
            departure: '18:00',
            duration: '18h 40m',
            arrival: '12:40',
            fare: 1200,
            seatAvailable: 15,
            bustype: 'AC Sleeper(2+1)',
            rating: 4.5,
            source: "Nagpur" ,
            destination: 'Mumbai',
        },
        {
            busId:"P32223",
            name: 'Purple Travels',
            departure: '20:00',
            duration: '16h 40m',
            arrival: '12:40',
            fare: 1200,
            seatAvailable: 15,
            bustype: 'AC Sleeper(2+1)',
            rating: 4.5,
            source: "Nagpur" ,
            destination: 'Pune',
        },
        {
            busId:"R32313",
            name: 'Royal Travels',
            departure: '20:00',
            duration: '16h 40m',
            arrival: '12:40',
            fare: 1200,
            seatAvailable: 15,
            bustype: 'AC Sleeper(2+1)',
            rating: 4.5,
            source: "Nagpur" ,
            destination: 'Kolhapur',
        },
      ],
    };
    export default busInfo;